# docker-compose -f docker-compose.yml up -d

version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: concert
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3307:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'
volumes:
  mysqldata: