spring:
  application:
    name: server-construction

  datasource:
    url: jdbc:mysql://localhost:3307/concert
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      data-locations: classpath*:init-scripts/data.sql
      continue-on-error: true

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create # (none, create, create-drop, update, validate)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level.org.hibernate:
    SQL: DEBUG
    orm.jdbc.bind: TRACE

# swagger ??
springdoc:
  swagger-ui:
    path: /swagger-index
    disable-swagger-default-url: true