spring:
  application:
    name: server-construction

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create # DB ??? ?? (none, create, create-drop, update, validate)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true # ?? ?? ?? (??)
        show_sql: true # ?? ?? ??
    defer-datasource-initialization: true

logging:
  level.org.hibernate:
    SQL: DEBUG
    orm.jdbc.bind: TRACE

# swagger ??
springdoc:
  swagger-ui:
    path: /swagger-index
    disable-swagger-default-url: true