openapi: 3.0.0
info:
  title: Concert Reservation API
  version: 1.0.0
  description: Concert reservation API documentation

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /concerts:
    get:
      summary: Get list of available concerts
      responses:
        '200':
          description: A list of concerts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                      example: "concert"